# Generated by Django 4.0.3 on 2022-03-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_categorie', models.CharField(max_length=255, unique=True, verbose_name='Titre catégorie')),
                ('lien_categorie', models.URLField(blank=True, default=None, null=True, verbose_name='Lien catégorie')),
                ('meta_description_categorie', models.TextField(verbose_name='Meta-déscription')),
                ('h1_categorie', models.CharField(max_length=150, verbose_name='H1')),
                ('paragraphe_categorie', models.TextField(verbose_name='Paragraphe')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Cible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cible', models.CharField(max_length=255, unique=True, verbose_name='Cible')),
            ],
            options={
                'verbose_name': 'Cible',
                'verbose_name_plural': 'Cible',
            },
        ),
        migrations.CreateModel(
            name='GroupeDeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_groupe_de_produit', models.CharField(max_length=255, unique=True, verbose_name='Titre groupe de produit')),
                ('lien_groupe_de_produit', models.URLField(blank=True, default=None, null=True, verbose_name='Lien groupe de produit')),
                ('meta_description_groupe_de_produit', models.TextField(verbose_name='Meta-déscription')),
                ('h1_groupe_de_produit', models.CharField(max_length=150, verbose_name='H1')),
                ('paragraphe_groupe_de_produit', models.TextField(verbose_name='Paragraphe')),
            ],
            options={
                'verbose_name': 'Groupe de produit',
                'verbose_name_plural': 'Groupe de produits',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_produit', models.CharField(max_length=255, unique=True, verbose_name='Titre produit')),
                ('lien_produit', models.URLField(blank=True, default=None, null=True, verbose_name='Lien produit')),
                ('meta_description_produit', models.TextField(verbose_name='Meta-déscription')),
                ('h1_produit', models.CharField(max_length=150, verbose_name='H1')),
                ('paragraphe_produit', models.TextField(verbose_name='Paragraphe')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_style', models.CharField(max_length=255, unique=True, verbose_name='Titre style')),
                ('lien_style', models.URLField(blank=True, default=None, null=True, verbose_name='Lien style')),
                ('meta_description_style', models.TextField(verbose_name='Meta-déscription')),
                ('h1_style', models.CharField(max_length=150, verbose_name='H1')),
                ('paragraphe_style', models.TextField(verbose_name='Paragraphe')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vendeur', models.CharField(max_length=150, verbose_name='Nom vendeur')),
                ('type_vendeur', models.CharField(choices=[('V', 'Vendeur'), ('C', 'Créateur')], default='V', max_length=2, verbose_name='Type vendeur')),
                ('lien_vendeur', models.URLField(blank=True, default=None, null=True, verbose_name='Lien du vendeur')),
                ('pipass', models.BooleanField(default=False, verbose_name='Pipass')),
                ('contacter', models.BooleanField(default=False, verbose_name='Contacté')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='VendeurCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_vendeurcategorie', models.URLField(blank=True, default=None, null=True, verbose_name='Lien')),
                ('categorie', models.ManyToManyField(related_name='vendeurcategorie_categorie', to='vendeur.categorie', verbose_name='Categories')),
                ('cible', models.ManyToManyField(blank=True, related_name='vendeurcategorie_cible', to='vendeur.cible', verbose_name='Cible')),
                ('groupe_de_produit', models.ManyToManyField(blank=True, related_name='vendeurcategorie_groupe_de_produit', to='vendeur.groupedeproduit', verbose_name='Groupe de produit')),
                ('produit', models.ManyToManyField(blank=True, related_name='vendeurcategorie_produit', to='vendeur.produit', verbose_name='Produit')),
                ('style', models.ManyToManyField(blank=True, related_name='vendeurcategorie_style', to='vendeur.style', verbose_name='Style')),
                ('vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendeurcategorie_vendeur', to='vendeur.vendeur', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Vendeur categorie',
                'verbose_name_plural': 'Vendeur categories',
                'ordering': ('pk',),
            },
        ),
    ]
