# Generated by Django 4.0.3 on 2022-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendeurcategorie',
            options={'ordering': ('pk',), 'verbose_name': 'Produit de vendeur', 'verbose_name_plural': 'Produits de vendeur'},
        ),
        migrations.AlterField(
            model_name='categorie',
            name='h1_categorie',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='H1'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='meta_description_categorie',
            field=models.TextField(blank=True, null=True, verbose_name='Meta-déscription'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='paragraphe_categorie',
            field=models.TextField(blank=True, null=True, verbose_name='Paragraphe'),
        ),
        migrations.AlterField(
            model_name='groupedeproduit',
            name='h1_groupe_de_produit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='H1'),
        ),
        migrations.AlterField(
            model_name='groupedeproduit',
            name='meta_description_groupe_de_produit',
            field=models.TextField(blank=True, null=True, verbose_name='Meta-déscription'),
        ),
        migrations.AlterField(
            model_name='groupedeproduit',
            name='paragraphe_groupe_de_produit',
            field=models.TextField(blank=True, null=True, verbose_name='Paragraphe'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='h1_produit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='H1'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='meta_description_produit',
            field=models.TextField(blank=True, null=True, verbose_name='Meta-déscription'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='paragraphe_produit',
            field=models.TextField(blank=True, null=True, verbose_name='Paragraphe'),
        ),
        migrations.AlterField(
            model_name='style',
            name='h1_style',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='H1'),
        ),
        migrations.AlterField(
            model_name='style',
            name='meta_description_style',
            field=models.TextField(blank=True, null=True, verbose_name='Meta-déscription'),
        ),
        migrations.AlterField(
            model_name='style',
            name='paragraphe_style',
            field=models.TextField(blank=True, null=True, verbose_name='Paragraphe'),
        ),
    ]
