# Generated by Django 4.0.3 on 2022-03-04 09:27

import django.contrib.postgres.fields.citext
from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0005_categorie_utilisateur_groupedeproduit_utilisateur_and_more'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='categorie',
            name='titre_categorie',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='Titre catégorie'),
        ),
    ]
