# Generated by Django 4.0.3 on 2022-03-04 10:26

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0006_alter_categorie_titre_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupedeproduit',
            name='titre_groupe_de_produit',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='Titre groupe de produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='titre_produit',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='Titre produit'),
        ),
        migrations.AlterField(
            model_name='style',
            name='titre_style',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='Titre style'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='lien_vendeur',
            field=models.URLField(default=None, verbose_name='Lien du vendeur'),
        ),
        migrations.AlterField(
            model_name='vendeurcategorie',
            name='cible',
            field=models.ManyToManyField(related_name='vendeurcategorie_cible', to='vendeur.cible', verbose_name='Cible'),
        ),
        migrations.AlterField(
            model_name='vendeurcategorie',
            name='groupe_de_produit',
            field=models.ManyToManyField(related_name='vendeurcategorie_groupe_de_produit', to='vendeur.groupedeproduit', verbose_name='Groupe de produit'),
        ),
        migrations.AlterField(
            model_name='vendeurcategorie',
            name='lien_vendeurcategorie',
            field=models.URLField(default=None, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='vendeurcategorie',
            name='produit',
            field=models.ManyToManyField(related_name='vendeurcategorie_produit', to='vendeur.produit', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='vendeurcategorie',
            name='style',
            field=models.ManyToManyField(related_name='vendeurcategorie_style', to='vendeur.style', verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='vendeurcategorie',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendeurcategorie_vendeur', to='vendeur.vendeur', verbose_name='Vendeur'),
        ),
    ]
