# Generated by Django 4.0.3 on 2022-03-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0008_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeurcategorie',
            name='style',
            field=models.ManyToManyField(blank=True, related_name='vendeurcategorie_style', to='vendeur.style', verbose_name='Style'),
        ),
    ]
