# Generated by Django 4.0.3 on 2022-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0009_alter_vendeurcategorie_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeurcategorie',
            name='lien_vendeurcategorie',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='URL'),
        ),
    ]
