# Generated by Django 4.0.3 on 2022-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0011_alter_groupedeproduit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='page_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Page title'),
        ),
        migrations.AddField(
            model_name='groupedeproduit',
            name='page_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Page title'),
        ),
        migrations.AddField(
            model_name='produit',
            name='page_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Page title'),
        ),
        migrations.AddField(
            model_name='style',
            name='page_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Page title'),
        ),
    ]
