# Generated by Django 4.0.2 on 2022-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_product_seller_alter_seller_city_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cible',
            field=models.ManyToManyField(blank=True, related_name='product_cible', to='seller.Cible', verbose_name='Cible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sous_category',
            field=models.ManyToManyField(blank=True, related_name='product_sous_categories', to='seller.SousCategories', verbose_name='Sous-categorie'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cible',
            field=models.ManyToManyField(blank=True, related_name='service_cible', to='seller.Cible', verbose_name='Cible'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sous_category',
            field=models.ManyToManyField(blank=True, related_name='service_sous_categories', to='seller.SousCategories', verbose_name='Sous-categorie'),
        ),
    ]
