# Generated by Django 4.0.2 on 2022-03-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='processed_status',
            field=models.BooleanField(default=False, verbose_name='Traiter status'),
        ),
    ]
