# Generated by Django 4.0.2 on 2022-03-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_alter_product_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='product_collections', to='seller.Collection', verbose_name='Collections'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(max_length=150, verbose_name='Titre du produit'),
        ),
    ]
