# Generated by Django 4.0.2 on 2022-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_alter_product_collections_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ('seller_name',), 'verbose_name': 'Vendeur', 'verbose_name_plural': 'Vendeurs'},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Prix'),
        ),
    ]
