# Generated by Django 4.0.2 on 2022-03-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_alter_seller_options_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, max_length=2, related_name='product_color', to='seller.Colors', verbose_name='Couleur produit'),
        ),
    ]
