# Generated by Django 4.0.2 on 2022-03-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_remove_product_color_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pipass',
            field=models.BooleanField(default=False, verbose_name='Pipass'),
        ),
    ]
