# Generated by Django 4.0.2 on 2022-02-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_product_cible_alter_product_sous_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_offer', models.CharField(max_length=255, unique=True, verbose_name='Offre type')),
            ],
            options={
                'verbose_name': 'Offer type',
                'verbose_name_plural': 'Offer types',
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='product',
            name='offer_type',
            field=models.ManyToManyField(related_name='product_offer_type', to='seller.OfferType', verbose_name="Type d'offre"),
        ),
    ]
