# Generated by Django 4.0.2 on 2022-02-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_offertype_delete_service_product_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, max_length=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='seller.colors', verbose_name='Couleur produit'),
        ),
    ]
