# Generated by Django 4.0.2 on 2022-03-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_product_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(null=True, related_name='product_collections', to='seller.Collection', verbose_name='Collections'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('NC', 'Non contacté'), ('NI', 'Non inscrit'), ('PR', 'Pas de réponse'), ('GR', 'Gratuit'), ('PA', 'Payant')], default='NC', max_length=2, verbose_name='Status du vendeur'),
        ),
    ]
