# Generated by Django 4.0.2 on 2022-03-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_alter_product_collections_alter_seller_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_collections', to='seller.Collection', verbose_name='Collections'),
        ),
    ]
